### ISSUE TITLE
wooden floors should require light support only

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#25]
Reported by: Captain Lurmey
Description:
I just noticed.. How comes wooden floors require "heavy" support while wooden walls only require "light" support? xD

**Comment by InsanityPrelude** [comment]
Not a bug. All player-buildable terrain types that aren't specifically bridges support Light, Medium, and Heavy structures. If a floor type exists which can be placed on a terrain which a wall can't be placed on, and afterwards you can build a wall on that, then you've de-facto made a bridge. (Or foundation, which is a different mod.)

Tellingly, this isn't a thing in the base game. All base game and royalty floor types require terrain that supports Heavy. Because they all support anything that can be built on top of them and there's no mechanism for the game to remember "original-terrain-type" or something, if this was "fixed" then you could just build wood across terrain like soft sand and then build anything you wanted on it. Added items which offer this functionality are beyond the scope of this mod.

**Comment by FluffierThanThou** [comment]
yay, I like this. Closing issues left and right.
