### ISSUE TITLE
ugly and basic floors cost the same?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#29]
Reported by: Hu Flung Dung
Description:
The cost of floors has changed.. dunno if this mod makes changes to cost but now floors with a beauty of 2 cost the same as floors with no beauty. Slabs cost 4 blocks &amp; mosaic tiles cost 4 blocks for example.

**Comment by InsanityPrelude** [comment]
This is correct.  It's like this in the vanilla game too, the difference is in the amount of work required.

The 0 beauty tiles get laid a great deal quicker than the pretty tiles.  The amount of stone needed to lay flooring doesn't change just because you're carefully cutting it up and putting the bricks into mosaic patterns, but it's a lot more work than just dropping in square slabs.

**Comment by FluffierThanThou** [comment]
thanks :)_
