### ISSUE TITLE
better way of handling chequerboard floors?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#7]
Rimworld A17 added in some new floor types. The textures are already greyscaled. 
Terrain/Surfaces/TileStone
Terrain/Surfaces/Flagstone

I figured I'd post this here, in case you could impliment the additional tiles.

**Comment by cucumpear** [comment]
I've made both for personal use if you'd like to use them. https://github.com/cucumpear/Stuffed-Floors-Add-On
And idk if you'd be interested, but that repository also includes the workaround I'm using for chequerboard floors.

**Comment by FluffierThanThou** [comment]
Would you mind walking me through how that chequerboard workaround works? I've never really used the random graphics class, nor have I seen an overlay used before...

**Comment by FluffierThanThou** [comment]
tiles/flagstone implemented. 

I'm interested in that chequerboard workaround, so keeping the issue open.

**Comment by cucumpear** [comment]
Basically it's just a 2x2 tiled floor (all textures are currently cannibalised from Telkir's tiles for now, because I'm terrible at that kind of thing) as base and then the half-transparent overlays. I wouldn't say the random graphics class is really necessary for a chequerboard and I'm not sure it behaves consistently random with a draggable object. At least with the stepping stone path I'm working on it seems to pull them in sequence sometimes.
Actually, now that I think about it it would probably be smarter to make a clean base and have all the shading for texture/grout on the overlay, that way it would be easier to make different overlay designs and wood/metal/stone variants.
Tbh mostly I wanted to point out the base-and-overlay option.

**Comment by FluffierThanThou** [comment]
so if I understand correctly, stuff colour is only applied to the overlay?

**Comment by FluffierThanThou** [comment]
oh, I think I just got the idea. It's not actually black magic, you're putting down a 'primer' floor, and then using a floor disguised as a building on top of that to create the pattern.

That seems a bit cumbersome to use for (and explain to) the average steam user...

**Comment by cucumpear** [comment]
Yeah, but I'm fairly certain it's the only reasonable way to do a quasi-stuffed chequerboard without having a fixed material. And I really don't think that would work at all for people with modded materials.
